# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GithubRN' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GithubRN

 
 # Umeng公共基础
    pod 'UMCCommon'
    pod 'UMCSecurityPlugins'
    pod 'UMCCommonLog'
    
    # 统计
    pod 'UMCAnalytics'
    
    # 分享与登录
    # U-Share SDK UI模块（分享面板，建议添加）
    pod 'UMCShare/UI'
    
    # 集成微信(精简版0.2M)
    pod 'UMCShare/Social/ReducedWeChat'
    
    # 集成QQ/QZone/TIM(精简版0.5M)
    pod 'UMCShare/Social/ReducedQQ'
    
    # 集成新浪微博(精简版1M)
    pod 'UMCShare/Social/ReducedSina'
    
    # 集成邮件
    pod 'UMCShare/Social/Email'
    
    # 集成短信
    pod 'UMCShare/Social/SMS'
    # pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'
    
  # pod 'react-native-webview', :path => '../node_modules/react-native-webview'

end


